root: true

env:
  browser: true
  jquery: true
  node: true
  amd: true

parser: babel-eslint

extends: eslint:recommended

globals:
  wp: true,
  Cookies: true,
  tofinoJS: true

rules:
  no-console: 0
