options:
  formatter: stylish
  
rules:
  # Extends
  placeholder-in-extend: 0

  # Style Guide
  property-sort-order: 0

  # Important
  no-important: 0

  # Nesting
  nesting-depth:
    - 1
    -
      max-depth: 4
